#!/bin/bash

echo "=========================================="
echo "GitHub Push Helper Script"
echo "=========================================="
echo ""
echo "Your project is ready to push to GitHub!"
echo ""
echo "To complete the sync, you need a Personal Access Token."
echo ""
echo "Step 1: Create a token (takes 30 seconds)"
echo "  1. Open: https://github.com/settings/tokens/new"
echo "  2. Note: 'Universal Data Converter'"
echo "  3. Expiration: Choose your preference"
echo "  4. Select scope: ✓ repo"
echo "  5. Click 'Generate token'"
echo "  6. Copy the token (starts with ghp_)"
echo ""
echo "Step 2: Create the repository"
echo "  1. Open: https://github.com/new"
echo "  2. Repository name: universal-data-converter"
echo "  3. Description: A powerful web-based tool for converting between JSON, YAML, XML, and CSV"
echo "  4. Choose Public or Private"
echo "  5. DO NOT initialize with README"
echo "  6. Click 'Create repository'"
echo ""
echo "Step 3: Push your code"
echo "  Run: git push -u origin main"
echo "  Username: Advikagarwal"
echo "  Password: [Paste your token here]"
echo ""
echo "=========================================="
echo "Your local repository is configured:"
echo "  - Git user: Advikagarwal"
echo "  - Git email: advikagarwal843@gmail.com"
echo "  - Remote: https://github.com/Advikagarwal/universal-data-converter.git"
echo "  - Branch: main"
echo "  - Files committed: 78 files"
echo "=========================================="
